import "./globals.css";
import NavBar from "@/components/common/navbar/NavBar";
import Footer from "@/components/common/footer/Footer";
import {
  poppins,
  openSans,
  ropaSans,
  quicksand,
  playfairDisplay,
} from "@/fonts/fonts";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <main
          className={`${openSans.variable} ${poppins.variable} ${quicksand.variable} ${ropaSans.variable} ${playfairDisplay.variable}`}
        >
          <NavBar />
          {children}
          <Footer />
        </main>
      </body>
    </html>
  );
}
